### PR TITLE
Compression is essential

### PR DESCRIPTION
**Pull request by QmelZ**
also please change the repo name to "chiptunestry" or something its not "chipetune" its "chiptune"

### CODE REVIEW

**Comment by ThatOneBepis** [comment]
you aren't wrong

**Comment by QmelZ** [comment]
yes

**Comment by ThatOneBepis** [comment]
also, it sucks that you cannot add github topics on phone

**Comment by QmelZ** [comment]
> also, it sucks that you cannot add github topics on phone

yes, try using "show desktop site"

**Pull request merged**
